//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessDetail
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> ChangePasswordDate { get; set; }
        public Nullable<int> LoginTypeID { get; set; }
        public string Description { get; set; }
        public long ItemID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual LoginType LoginType { get; set; }
    }
}
