//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionPaneCategoriesLink
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActionPaneCategoriesLink()
        {
            this.ActionPaneCategoriesLinks1 = new HashSet<ActionPaneCategoriesLink>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string NavigateUrl { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionPaneCategoriesLink> ActionPaneCategoriesLinks1 { get; set; }
        public virtual ActionPaneCategoriesLink ActionPaneCategoriesLink1 { get; set; }
    }
}
