//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDocindex
    {
        public int NoteID { get; set; }
        public int SystemID { get; set; }
        public string NoteDesc { get; set; }
        public string NoteData { get; set; }
        public Nullable<int> IndexOrder { get; set; }
        public Nullable<int> DocIndexId { get; set; }
        public Nullable<int> DocLanguageAlg { get; set; }
    }
}
