//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppErrorCode
    {
        public int ID { get; set; }
        public int ErrorID { get; set; }
        public int SectionID { get; set; }
        public string ErrorDescription { get; set; }
    }
}
