//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationsSecurityStatu
    {
        public int SecurityStatusID { get; set; }
        public Nullable<int> SecurityStatusAuditStatusID { get; set; }
        public Nullable<System.DateTime> SecurityStatusLastUpdate { get; set; }
        public string SecurityStatusReason { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<bool> SIEMReady { get; set; }
        public Nullable<bool> SOX { get; set; }
        public Nullable<int> RiskAssessmentId { get; set; }
        public Nullable<bool> PCI { get; set; }
        public Nullable<System.DateTime> DateAuditPermission { get; set; }
        public Nullable<bool> CoreSystem { get; set; }
        public Nullable<bool> CyberCompliance { get; set; }
    }
}
