//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationsLog
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Manager { get; set; }
        public string TopologyFileName { get; set; }
        public Nullable<bool> IsSubsystem { get; set; }
        public Nullable<bool> IsOpenSystem { get; set; }
        public Nullable<bool> IsInfrastructure { get; set; }
        public Nullable<int> CriticalLevelID { get; set; }
        public string Alias { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<bool> HasDRP { get; set; }
        public Nullable<bool> IsProprietary { get; set; }
        public Nullable<bool> HasDevelopementEnv { get; set; }
        public Nullable<bool> HasStagingEnv { get; set; }
        public string SLA { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> EnabledDRP { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string ShadowName { get; set; }
        public string UserGUID { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> PermissionEnable { get; set; }
        public string Instruction { get; set; }
        public Nullable<int> SensitivityID { get; set; }
        public string SensitivityDesc { get; set; }
        public string NamingConvention { get; set; }
        public string SysUserId { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string Operation { get; set; }
        public string ApplicationsVersion { get; set; }
        public string WorkflowID { get; set; }
        public string SystemUserName { get; set; }
        public Nullable<bool> SOX { get; set; }
        public Nullable<bool> SIEMReady { get; set; }
        public Nullable<bool> Pci { get; set; }
        public Nullable<System.DateTime> DateAuditPermission { get; set; }
        public Nullable<int> SecurityStatusAuditStatusID { get; set; }
        public Nullable<System.DateTime> SecurityStatusLastUpdate { get; set; }
        public string HealthCheckList { get; set; }
        public string RoleOwnerList { get; set; }
        public Nullable<int> StatusID { get; set; }
    }
}
