//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationOperation
    {
        public int ID { get; set; }
        public int AppID { get; set; }
        public string ManageAddress { get; set; }
        public string PurchaseOrder { get; set; }
        public Nullable<decimal> MetaItemCost { get; set; }
        public Nullable<decimal> MetaItemCostDollar { get; set; }
        public string YearMaintenan { get; set; }
    }
}
