//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationMaintenance
    {
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public Nullable<System.DateTime> InstallTimeStamp { get; set; }
        public Nullable<System.DateTime> PurchaseTimeStamp { get; set; }
        public Nullable<System.DateTime> WarrentyStartDate { get; set; }
        public Nullable<System.DateTime> WarrentyEndDate { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<System.DateTime> OutServiceDate { get; set; }
        public Nullable<System.DateTime> InformationsecurityLastUpdate { get; set; }
        public Nullable<int> ServiceContactID { get; set; }
    }
}
