//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AthorMethorRight
    {
        public int ModuleRightsID { get; set; }
        public int ModuleID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string UserLname { get; set; }
        public string UserGuid { get; set; }
        public string UserFullName { get; set; }
    }
}
