//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AthorPagesRight
    {
        public int AthorPageId { get; set; }
        public int PageID { get; set; }
        public int ModuleRightID { get; set; }
        public string UserID { get; set; }
        public Nullable<bool> Read { get; set; }
        public Nullable<bool> Write { get; set; }
        public Nullable<bool> Delete { get; set; }
        public string UserFullName { get; set; }
    }
}
