//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoTestServer
    {
        public int Id { get; set; }
        public int AutoTestId { get; set; }
        public int ServerId { get; set; }
        public string ServerName { get; set; }
        public Nullable<bool> Selected { get; set; }
        public string Remark { get; set; }
        public string RelatedToSubSystems { get; set; }
    
        public virtual AutoTest AutoTest { get; set; }
    }
}
