//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoTestSubSystem
    {
        public int Id { get; set; }
        public int AutoTestId { get; set; }
        public int SystemId { get; set; }
        public string SystemName { get; set; }
        public string Remark { get; set; }
    
        public virtual AutoTest AutoTest { get; set; }
    }
}
