//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BizProcess()
        {
            this.BizProcessApplications = new HashSet<BizProcessApplication>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CriticalLevelID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string ProcessManager { get; set; }
        public string Description { get; set; }
    
        public virtual BizProcessType BizProcessType { get; set; }
        public virtual CriticalLevel CriticalLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BizProcessApplication> BizProcessApplications { get; set; }
    }
}
