//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CableItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CableItem()
        {
            this.CableItem1 = new HashSet<CableItem>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<long> SourceId { get; set; }
        public Nullable<int> SourcePort { get; set; }
        public Nullable<long> DestinationID { get; set; }
        public Nullable<int> DestinationPort { get; set; }
        public string CableNumber { get; set; }
        public string Tasks { get; set; }
        public Nullable<long> Sort { get; set; }
        public Nullable<int> Length { get; set; }
    
        public virtual CableColor CableColor { get; set; }
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CableItem> CableItem1 { get; set; }
        public virtual CableItem CableItem2 { get; set; }
        public virtual PhysicalInterface PhysicalInterface { get; set; }
        public virtual PhysicalInterface PhysicalInterface1 { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual CableType CableType { get; set; }
    }
}
