//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Captcha
    {
        public int Id { get; set; }
        public bool Success { get; set; }
        public string ErrorCodes { get; set; }
        public string Hostname { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string IP { get; set; }
    }
}
