//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CloudInfoForSystem
    {
        public int Id { get; set; }
        public int SystemId { get; set; }
        public Nullable<int> CloudProviderId { get; set; }
        public string ServiceProvider { get; set; }
        public Nullable<int> HostingLocationId { get; set; }
        public Nullable<int> RedundancyLevelId { get; set; }
        public string Remarks { get; set; }
    
        public virtual CloudHostingLocationForSystem CloudHostingLocationForSystem { get; set; }
        public virtual CloudProviderForSystem CloudProviderForSystem { get; set; }
        public virtual CloudRedundancyLevelForSystem CloudRedundancyLevelForSystem { get; set; }
    }
}
