//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cluster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cluster()
        {
            this.ClusterItemMembers = new HashSet<ClusterItemMember>();
            this.Items = new HashSet<Item>();
        }
    
        public int ClusterID { get; set; }
        public string ClusterName { get; set; }
        public string ClusterDescription { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> IsSubCluster { get; set; }
        public string ClusterVIP { get; set; }
        public Nullable<int> ClusterTypeID { get; set; }
        public Nullable<int> ClusterMethodID { get; set; }
        public Nullable<int> ClusterProtocolID { get; set; }
        public Nullable<bool> ClusterFileLeveBackup { get; set; }
        public Nullable<bool> ClusterTDPBackup { get; set; }
        public string ClusterBackupRemark { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClusterItemMember> ClusterItemMembers { get; set; }
        public virtual ClusterType ClusterType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
