//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboCatalog
    {
        public int ID { get; set; }
        public Nullable<int> ActionID { get; set; }
        public string SPName { get; set; }
        public string Header1 { get; set; }
        public string Header2 { get; set; }
    }
}
