//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationLineRealatedSystem
    {
        public int RealatedSystemID { get; set; }
        public int LineID { get; set; }
        public int SystemID { get; set; }
        public string Description { get; set; }
    }
}
