//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationLineLink
    {
        public int ID { get; set; }
        public string LinkDesc { get; set; }
        public int ComLineID { get; set; }
        public string LinkUrl { get; set; }
    }
}
