//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationLine
    {
        public int CommunicationLineID { get; set; }
        public int EnviromentID { get; set; }
        public string Description { get; set; }
        public int PurposeID { get; set; }
        public int StatusID { get; set; }
        public string Serial { get; set; }
        public string ClusterName { get; set; }
        public string Workflow { get; set; }
        public string SourceLocationCity { get; set; }
        public string SourceLocationBuillding { get; set; }
        public string SourceLocationCountry { get; set; }
        public string SourceLocationFloor { get; set; }
        public string SourceLocationRoom { get; set; }
        public string DestinationLocationCity { get; set; }
        public string DestanationLocationBuilding { get; set; }
        public string DestanetionLocationCountry { get; set; }
        public string DestanetionLocationFloor { get; set; }
        public string DestanationLocationRoom { get; set; }
        public string CommunicationLineCode { get; set; }
        public Nullable<int> CommunicationLineISPID { get; set; }
        public Nullable<int> CommunicationLineKindID { get; set; }
        public Nullable<int> CommunicationLineBandwidthID { get; set; }
        public Nullable<System.DateTime> InsertTimeStamp { get; set; }
        public Nullable<System.DateTime> InstallTimeStamp { get; set; }
        public Nullable<System.DateTime> WarrentyStartDate { get; set; }
        public Nullable<System.DateTime> WarrentyEndDate { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<int> CriticalLevelID { get; set; }
        public Nullable<System.DateTime> OutServiceDate { get; set; }
        public Nullable<System.DateTime> SecurityLastUpdate { get; set; }
        public Nullable<bool> VPN { get; set; }
        public Nullable<int> LineTypeId { get; set; }
        public Nullable<int> CommunicationLineInfrastructureProviderID { get; set; }
        public string BusinessOwner { get; set; }
        public string LineOwner { get; set; }
        public string SecondLineID { get; set; }
        public Nullable<int> CommunicationLineParentID { get; set; }
        public string DestanationLocationRack { get; set; }
        public string SourceLocationRack { get; set; }
        public string CommunicationLineVlan { get; set; }
        public Nullable<decimal> UploadBandwidth { get; set; }
        public Nullable<decimal> DownloadBandwidth { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Commnats { get; set; }
    
        public virtual CommunicationLineBandwidth CommunicationLineBandwidth { get; set; }
        public virtual CommunicationLineISP CommunicationLineISP { get; set; }
        public virtual CommunicationLineKind CommunicationLineKind { get; set; }
    }
}
