//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationLineHop
    {
        public int CommunicationLineHopsID { get; set; }
        public int CommunicationLineID { get; set; }
        public int HopNum { get; set; }
        public Nullable<int> HopCountry { get; set; }
        public Nullable<int> HopCity { get; set; }
        public Nullable<int> HopBuilding { get; set; }
        public Nullable<int> HopRoom { get; set; }
        public Nullable<int> HopRack { get; set; }
        public Nullable<int> HopFloor { get; set; }
    }
}
