//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPerson
    {
        public int ContactID { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string ContactTittle { get; set; }
        public Nullable<int> ContactCompanyID { get; set; }
        public string ContactPhoneNumber { get; set; }
        public string ContactEmail { get; set; }
        public string ContactAdditionalEmail { get; set; }
        public string ContactPhone { get; set; }
        public string ContactFax { get; set; }
        public string ContactMobile { get; set; }
        public string ContactPrivateAddress { get; set; }
        public string ContactPrivateCity { get; set; }
        public string ContactPrivateZip { get; set; }
        public string ContactPrivateCountry { get; set; }
        public string ContactPrivateWebPage { get; set; }
        public string ContactPrivateBitthday { get; set; }
        public string ContactWorkTittle { get; set; }
        public string ContactWorkDepartment { get; set; }
        public string ContactWorkOrganization { get; set; }
        public string ContactWorkAddress { get; set; }
        public string ContactWorkZip { get; set; }
        public string ContactWorkCountry { get; set; }
        public string ContactWorkWebPage { get; set; }
        public string ContactPersonsDescription { get; set; }
        public string ContactPersonDirectManage { get; set; }
        public string ContactPersonExternalManager { get; set; }
        public Nullable<int> ContactPersonRoleID { get; set; }
    }
}
