//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseInstance
    {
        public int ID { get; set; }
        public Nullable<bool> IsCluster { get; set; }
        public string ClusterName { get; set; }
        public string AdminSystemPwd { get; set; }
        public string AdminOraclePwd { get; set; }
        public Nullable<int> RetentionPeriod { get; set; }
        public Nullable<System.DateTime> LastFullBackup { get; set; }
        public Nullable<int> BackupLevel { get; set; }
        public Nullable<int> BackupType { get; set; }
        public string LastBackupStatus { get; set; }
        public string BackupJobName { get; set; }
        public Nullable<int> ListenerPort { get; set; }
        public string LogonTriggerStatus { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> BackupTypeExp { get; set; }
        public Nullable<bool> BackupTypeRMAN { get; set; }
        public string DBType { get; set; }
        public Nullable<int> DBVersion { get; set; }
        public Nullable<bool> IsASM { get; set; }
        public string Owner { get; set; }
        public Nullable<int> BackupAgent { get; set; }
        public Nullable<System.DateTime> DateDefined { get; set; }
        public string AlertscanRun { get; set; }
        public string PhysicalLocation { get; set; }
        public Nullable<bool> HasDRP { get; set; }
        public Nullable<bool> Obsolete { get; set; }
        public string RemoteControl { get; set; }
        public Nullable<int> CriticalLevelID { get; set; }
        public Nullable<int> Frontend { get; set; }
        public string DownTime { get; set; }
        public Nullable<int> RecoveryPoint { get; set; }
        public Nullable<int> MachineAvailablity { get; set; }
        public string DBClusterName { get; set; }
        public string DBName { get; set; }
        public Nullable<long> HostName { get; set; }
        public string HostIp { get; set; }
        public string Location { get; set; }
        public string OperationSystem { get; set; }
        public string Parent { get; set; }
        public string Rack { get; set; }
        public string RelativeLocation { get; set; }
        public string CatalogNumber { get; set; }
        public string Container { get; set; }
        public string IP_OOB { get; set; }
        public Nullable<int> ClusterID { get; set; }
        public Nullable<int> DatabaseID { get; set; }
        public string ListenerName { get; set; }
        public string InstanceName { get; set; }
        public string DatabaseName { get; set; }
        public string Edition { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ClassificationID { get; set; }
        public string Schema { get; set; }
        public Nullable<int> IsMain { get; set; }
    
        public virtual CriticalLevel CriticalLevel { get; set; }
    }
}
