//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMO
    {
        public int ID { get; set; }
        public int SourceApplicationID { get; set; }
        public int TargetApplicationID { get; set; }
        public Nullable<bool> IsBidirectional { get; set; }
        public Nullable<bool> IsSynchrounous { get; set; }
        public Nullable<bool> IsBatch { get; set; }
        public Nullable<int> ProtocolID { get; set; }
        public Nullable<int> DataTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<int> CriticalLevelID { get; set; }
        public Nullable<bool> SendRecive { get; set; }
        public Nullable<int> FrequencyID { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<int> LobID { get; set; }
    }
}
