//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DownTime()
        {
            this.Applications = new HashSet<Application>();
            this.Items = new HashSet<Item>();
        }
    
        public int ID { get; set; }
        public string DownTimeDesc { get; set; }
        public string DownTimeDay { get; set; }
        public string DownTimeWeek { get; set; }
        public string DownTimeMouth { get; set; }
        public string DownTimeDate { get; set; }
        public string DownTimeStartHour { get; set; }
        public string DownTimeEndHour { get; set; }
        public string DownTimeDurationTime { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
