//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DpItemHardware
    {
        public int Id { get; set; }
        public long DpItemId { get; set; }
        public string CPUType { get; set; }
        public Nullable<decimal> CPUSpeed { get; set; }
        public Nullable<decimal> OfCores { get; set; }
        public Nullable<decimal> Memory { get; set; }
        public Nullable<decimal> OfHardDrives { get; set; }
        public Nullable<decimal> TotalStorage { get; set; }
        public Nullable<decimal> CDriveSize { get; set; }
        public Nullable<decimal> DDriveSize { get; set; }
        public Nullable<decimal> EDriveSize { get; set; }
        public string FQDN { get; set; }
        public string UUID { get; set; }
        public string TBDA { get; set; }
        public string TBDB { get; set; }
        public string TBDC { get; set; }
        public string TBDD { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
