//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRPChecker
    {
        public int CheckerID { get; set; }
        public string Subsystem { get; set; }
        public Nullable<int> CheckerNumber { get; set; }
        public string EmployeeName { get; set; }
        public string PhoneNumber { get; set; }
        public string HomePhoneNumber { get; set; }
        public string Usernameemergencythawing { get; set; }
        public string Comments { get; set; }
        public string AttachedFile { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string CheckerNumber2 { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Uname { get; set; }
        public string GuidUser { get; set; }
        public Nullable<bool> Insurance { get; set; }
    }
}
