//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRPDocument
    {
        public int DocumentsForDRPID { get; set; }
        public Nullable<bool> ReadinessForDR { get; set; }
        public Nullable<bool> Testers { get; set; }
        public Nullable<bool> TestsScenarios { get; set; }
        public Nullable<bool> ExternaSoftware { get; set; }
        public Nullable<int> SystemID { get; set; }
    }
}
