//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRPEvent
    {
        public int ID { get; set; }
        public int SystemID { get; set; }
        public string EvetDescription { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsTested { get; set; }
        public int DR_EnumStatusID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
