//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRPPreparation
    {
        public int PreparationsID { get; set; }
        public int SystemID { get; set; }
        public Nullable<System.DateTime> PreparationsDate { get; set; }
        public string PreparationsDesc { get; set; }
        public string Specialrequirements { get; set; }
        public Nullable<int> EventType { get; set; }
        public string ExecuteResponsibility { get; set; }
        public string Involvedsource { get; set; }
        public string Comments { get; set; }
        public string AttachedFile { get; set; }
        public string PreparationsDateDesc { get; set; }
    }
}
