//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRPRequiredSoftware
    {
        public int RequiredSoftwareID { get; set; }
        public string SoftwareName { get; set; }
        public string Version { get; set; }
        public Nullable<int> Manufacturer { get; set; }
        public string SpecialRequirements { get; set; }
        public Nullable<int> Contactperson { get; set; }
        public string Presenceofthesupplier { get; set; }
        public Nullable<int> Supplier { get; set; }
        public string Comments { get; set; }
        public string Attachafile { get; set; }
        public Nullable<int> SystemID { get; set; }
        public string EmployeeName { get; set; }
    }
}
