//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectricalCircuite
    {
        public long ID { get; set; }
        public bool IsThreePhase { get; set; }
        public bool IsSinglePhase { get; set; }
        public string CircuiteNumber { get; set; }
        public Nullable<double> MaximumCapacityAmper { get; set; }
        public int RoomID { get; set; }
        public string Field { get; set; }
        public string Region { get; set; }
        public string Description { get; set; }
        public Nullable<int> SinglePhaseSign { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Rack Rack { get; set; }
    }
}
