//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class From_TADDM_to_LANSWEEPER
    {
        public int Id { get; set; }
        public string OS_Version { get; set; }
        public string Description { get; set; }
        public string IPAddress { get; set; }
        public string MACaddress { get; set; }
        public Nullable<long> LastChanged { get; set; }
        public Nullable<System.DateTime> LastChanged1 { get; set; }
        public string OS_INSTALLDATE { get; set; }
        public Nullable<System.DateTime> OS_INSTALLDATE1 { get; set; }
        public string Computername { get; set; }
        public string Harav { get; set; }
    }
}
