//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImporterLog
    {
        public int ID { get; set; }
        public string HostName { get; set; }
        public string Status { get; set; }
        public string ImporterCatalogName { get; set; }
        public string CatalogName { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<int> ActionID { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string RecordTypeID { get; set; }
        public Nullable<bool> IsRelevant { get; set; }
        public string CatalogNumber { get; set; }
        public string Description { get; set; }
        public string Owner { get; set; }
        public string Parent { get; set; }
        public string Rack { get; set; }
        public Nullable<int> StartingU { get; set; }
        public string ExtendedFields { get; set; }
        public string NICs { get; set; }
        public string ServerRoles { get; set; }
        public string OSName { get; set; }
    }
}
