//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IP
    {
        public string IPID { get; set; }
        public Nullable<int> VilanID { get; set; }
        public string HostName { get; set; }
        public string UserName { get; set; }
        public string Comment { get; set; }
    }
}
