//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemNIC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemNIC()
        {
            this.NICIPs = new HashSet<NICIP>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string MACAddress { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public string DNSServer { get; set; }
        public string DefaultGateway { get; set; }
        public string SubnetMask { get; set; }
        public string Switch { get; set; }
        public string VLAN { get; set; }
        public string Port { get; set; }
        public Nullable<int> VlanID { get; set; }
        public Nullable<int> TierID { get; set; }
        public Nullable<int> AreaID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual NICType NICType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NICIP> NICIPs { get; set; }
    }
}
