//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMetaData
    {
        public long ID { get; set; }
        public long ItemID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<int> MeasureUnitID { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> WeightTypeID { get; set; }
        public Nullable<int> USize { get; set; }
        public Nullable<int> UUnits { get; set; }
        public Nullable<short> Power { get; set; }
        public Nullable<short> ConsumePower { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
