//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemBackupDocument
    {
        public int DocumentID { get; set; }
        public string DocumentDesc { get; set; }
        public string DocumentLink { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<bool> DefualtPage { get; set; }
    }
}
