//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemData
    {
        public long ItemID { get; set; }
        public bool Siem { get; set; }
        public bool Pci { get; set; }
        public bool Sox { get; set; }
        public bool Sensitive { get; set; }
        public Nullable<bool> DataPrivilege { get; set; }
        public string StorageMethod { get; set; }
        public string ShutDownOrder { get; set; }
        public string PowerOnOrder { get; set; }
        public string WWN { get; set; }
        public Nullable<int> TypeOfUse { get; set; }
        public Nullable<long> AccessServer { get; set; }
        public Nullable<bool> Internet { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
