//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemEnergy
    {
        public int ItemID { get; set; }
        public Nullable<int> PowerSupply { get; set; }
        public Nullable<int> OperationVolatage { get; set; }
        public Nullable<int> PowerCords { get; set; }
        public string Power { get; set; }
        public string AVG { get; set; }
        public string LastSampelTime { get; set; }
    }
}
