//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemApplicationConnection
    {
        public int ID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<bool> ConnectForDb { get; set; }
        public Nullable<int> DBId { get; set; }
    }
}
