//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobFunctionToFix
    {
        public int Id { get; set; }
        public int ApplicationFunctionID { get; set; }
        public string NewPhoneNumber { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<bool> IsPersonMissing { get; set; }
        public Nullable<long> ObjectID { get; set; }
        public string ObjectName { get; set; }
    }
}
