//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LansweeperImport_Temp01
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Vendor { get; set; }
        public string SN { get; set; }
        public string CPUSpeed { get; set; }
        public Nullable<int> NumProcesses { get; set; }
        public string FQDN { get; set; }
        public Nullable<int> Memory { get; set; }
        public string UUID { get; set; }
        public Nullable<int> IsVirtual { get; set; }
        public string OS { get; set; }
        public string OSVersion { get; set; }
        public string NICNames { get; set; }
        public string NICIPs { get; set; }
        public string NICMACs { get; set; }
        public string LastDiscovered { get; set; }
        public string OSInstallDate { get; set; }
        public string model { get; set; }
        public string harav { get; set; }
    }
}
