//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOBALERT
    {
        public int ID { get; set; }
        public int LobID { get; set; }
        public string resourceIdPath { get; set; }
        public string severity { get; set; }
        public bool flag { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
