//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int ID { get; set; }
        public int RoomID { get; set; }
        public short RowIndex { get; set; }
        public short ColumnIndex { get; set; }
        public long ItemID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Room Room { get; set; }
    }
}
