//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDcmPlu
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TableName { get; set; }
        public int RecordId { get; set; }
        public string ChangeType { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string ChangeDetails { get; set; }
    
        public virtual User User { get; set; }
    }
}
