//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaintenanceCompany()
        {
            this.SystemMaintenanceCompanies = new HashSet<SystemMaintenanceCompany>();
            this.SystemMaintenanceCompanies1 = new HashSet<SystemMaintenanceCompany>();
            this.SystemMaintenanceCompanies2 = new HashSet<SystemMaintenanceCompany>();
            this.SystemMaintenanceCompanies3 = new HashSet<SystemMaintenanceCompany>();
            this.SystemMaintenanceCompanies4 = new HashSet<SystemMaintenanceCompany>();
            this.SystemMaintenanceCompanies5 = new HashSet<SystemMaintenanceCompany>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string CustomerPhone { get; set; }
        public string ContactPhone { get; set; }
        public string ContactName { get; set; }
        public string JobTitle { get; set; }
        public string EMail { get; set; }
        public string PhoneOffice { get; set; }
        public string PhoneHome { get; set; }
        public string PhoneCell { get; set; }
        public string Address { get; set; }
        public string SupplierNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemMaintenanceCompany> SystemMaintenanceCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemMaintenanceCompany> SystemMaintenanceCompanies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemMaintenanceCompany> SystemMaintenanceCompanies2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemMaintenanceCompany> SystemMaintenanceCompanies3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemMaintenanceCompany> SystemMaintenanceCompanies4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemMaintenanceCompany> SystemMaintenanceCompanies5 { get; set; }
    }
}
