//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public string Header { get; set; }
        public string Icon { get; set; }
        public string Link { get; set; }
        public Nullable<int> ParentID { get; set; }
        public bool Display { get; set; }
        public Nullable<int> IndexNumber { get; set; }
        public Nullable<bool> IsModule { get; set; }
    }
}
