//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MetaItem()
        {
            this.Items = new HashSet<Item>();
            this.Items1 = new HashSet<Item>();
            this.Items2 = new HashSet<Item>();
        }
    
        public long ID { get; set; }
        public long TypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<int> MeasureUnitID { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> WeightTypeID { get; set; }
        public Nullable<int> USize { get; set; }
        public Nullable<int> UUnits { get; set; }
        public Nullable<short> Power { get; set; }
        public Nullable<decimal> ConsumePower { get; set; }
        public int VisioMasterID { get; set; }
        public Nullable<int> BTULoad { get; set; }
        public int ManufacturerID { get; set; }
        public Nullable<int> MaxNumberOfPowerSupply { get; set; }
        public Nullable<bool> IsThreePhase { get; set; }
        public Nullable<bool> IsSinglePhase { get; set; }
        public Nullable<bool> TotalPowerVACalculate { get; set; }
        public Nullable<int> OperationVolatage { get; set; }
        public Nullable<int> NumberOfPowerCords { get; set; }
        public Nullable<bool> IsServer { get; set; }
        public Nullable<double> MetaItemCost { get; set; }
        public Nullable<int> ConnectionInterval { get; set; }
        public Nullable<int> ofPorts { get; set; }
        public bool Backendports { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items2 { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual MeasureUnit MeasureUnit { get; set; }
        public virtual VisioMaster VisioMaster { get; set; }
        public virtual WeightType WeightType { get; set; }
    }
}
