//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MND_SystemMovement
    {
        public int SystemID { get; set; }
        public Nullable<System.DateTime> MovementADate { get; set; }
        public Nullable<System.TimeSpan> MovementATime { get; set; }
        public Nullable<System.DateTime> MovementBDate { get; set; }
        public Nullable<System.TimeSpan> MovementBTime { get; set; }
        public Nullable<System.DateTime> MovementCDate { get; set; }
        public Nullable<System.TimeSpan> MovementCTime { get; set; }
        public Nullable<System.DateTime> MovementDDate { get; set; }
        public Nullable<System.TimeSpan> MovementDTime { get; set; }
    }
}
