//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNDEvent
    {
        public int EvetID { get; set; }
        public string EventDesc { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<System.TimeSpan> EventTime { get; set; }
        public string EventInformer { get; set; }
        public Nullable<int> MovementID { get; set; }
        public string Action { get; set; }
        public Nullable<int> EventTypeID { get; set; }
        public Nullable<System.TimeSpan> EvetCloseTime { get; set; }
        public Nullable<System.DateTime> EventCloseDate { get; set; }
        public Nullable<int> EventStatusID { get; set; }
    }
}
