//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNDMovement
    {
        public int MovementID { get; set; }
        public string Header { get; set; }
        public string MovementDesc { get; set; }
        public Nullable<System.DateTime> MovementDateDesire { get; set; }
        public Nullable<System.TimeSpan> MovementTimeDesire { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> IsSubMovement { get; set; }
        public string ManagerID { get; set; }
        public Nullable<System.DateTime> MovementDateClosed { get; set; }
        public Nullable<System.TimeSpan> MovementTimeClosed { get; set; }
        public Nullable<int> MovementStatusID { get; set; }
    }
}
