//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNDMovementSystemMember
    {
        public int MovmentID { get; set; }
        public int SystemID { get; set; }
        public Nullable<int> SystemStatus { get; set; }
        public Nullable<System.TimeSpan> DesireTime { get; set; }
        public Nullable<System.TimeSpan> RollBackTime { get; set; }
        public Nullable<bool> RollBackTimeFlag { get; set; }
        public Nullable<bool> DesireTimeFlag { get; set; }
        public Nullable<bool> ShowTimeWarning { get; set; }
        public Nullable<bool> IsWarningFlag { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<System.TimeSpan> DesireTimeStart { get; set; }
    }
}
