//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNDRiskBank
    {
        public int RiskID { get; set; }
        public string RiskName { get; set; }
        public Nullable<int> RiskStatusID { get; set; }
        public string RiskDesc { get; set; }
        public Nullable<int> RiskType { get; set; }
    }
}
