//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNDShipmentsLog
    {
        public int ShipmentLogId { get; set; }
        public int ShipmentId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.TimeSpan> LogTime { get; set; }
    }
}
