//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewLocation
    {
        public int NewLocationID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> RelativeLocation { get; set; }
        public Nullable<int> RackId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> VersionId { get; set; }
        public Nullable<bool> NewRearLocation { get; set; }
        public Nullable<bool> DefualtVersion { get; set; }
    }
}
