//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgTree
    {
        public int EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ParentEmployeeNumber { get; set; }
        public string UnitLevel { get; set; }
        public string Unit { get; set; }
        public string BelongsToLevel { get; set; }
        public string BelongsTo { get; set; }
        public string Position { get; set; }
    }
}
