//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageHeader
    {
        public int ID { get; set; }
        public int PageID { get; set; }
        public int MethodID { get; set; }
        public string Header { get; set; }
        public string dbFieldName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> GridID { get; set; }
        public string Defualt { get; set; }
        public string LabelID { get; set; }
    }
}
