//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalizationDisplay
    {
        public int ID { get; set; }
        public string Firts4000ch_Display { get; set; }
        public string Second4000ch_Display { get; set; }
        public string UserId { get; set; }
        public string PageName { get; set; }
    }
}
