//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class portalReport
    {
        public int ReportID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int SectionID { get; set; }
        public string LINK { get; set; }
    }
}
