//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.ProfileJobFunctions = new HashSet<ProfileJobFunction>();
            this.ProfileLocations = new HashSet<ProfileLocation>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public string Alias { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Section { get; set; }
        public string Manager { get; set; }
        public Nullable<bool> HasDevelopementEnv { get; set; }
        public Nullable<bool> HasStagingEnv { get; set; }
        public Nullable<bool> DevQAEnv { get; set; }
        public Nullable<bool> DevTestENV { get; set; }
        public Nullable<bool> HasAsEnv { get; set; }
        public Nullable<bool> HasDrp { get; set; }
        public Nullable<int> criticalLevel { get; set; }
        public string SLA { get; set; }
        public Nullable<int> DeprtmentID { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileJobFunction> ProfileJobFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileLocation> ProfileLocations { get; set; }
    }
}
