//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rack()
        {
            this.Items = new HashSet<Item>();
            this.ElectricalCircuites = new HashSet<ElectricalCircuite>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string SpaceID { get; set; }
        public string SN { get; set; }
        public string AssetNumber { get; set; }
        public string Barcode { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public string Model { get; set; }
        public long MetaItemID { get; set; }
        public Nullable<decimal> ReservedAmper { get; set; }
        public Nullable<decimal> MaxWeightCapacity { get; set; }
        public Nullable<int> BTULoad { get; set; }
        public short RackUnits { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<short> RowIndex { get; set; }
        public Nullable<short> ColumnIndex { get; set; }
        public string Attribution { get; set; }
        public string Project { get; set; }
        public string RowIndexB { get; set; }
        public int EnvironmentId { get; set; }
        public string Netoprice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectricalCircuite> ElectricalCircuites { get; set; }
    }
}
