//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerPropertiesLog
    {
        public int LogId { get; set; }
        public System.DateTime LogTimeStamp { get; set; }
        public string HostName { get; set; }
        public string Description { get; set; }
    }
}
