//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerProperty
    {
        public int ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string HOST_NAME { get; set; }
        public string TARGET_NAME { get; set; }
        public string TYPE { get; set; }
        public string VERSION { get; set; }
        public string PLATFORM { get; set; }
        public string OS_NAME { get; set; }
        public string OS_VENDOR { get; set; }
        public string BASE_VERSION { get; set; }
        public string UPDATE_LEVEL { get; set; }
        public string OS_DISTRIBUTER { get; set; }
        public string BIT_LEVEL { get; set; }
        public string ORACLE_HOME { get; set; }
        public string STARTUP_TIME { get; set; }
        public string VENDOR_NAME { get; set; }
        public string SYSTEM_CONFIG { get; set; }
        public string MACHINE_ARCH { get; set; }
        public string LOCAL_DISK_SPACE_GB { get; set; }
        public string MEMORY_SIZE_GB { get; set; }
        public string SWAP_SIZE_GB { get; set; }
        public string NO_OF_CPU { get; set; }
        public string NO_OF_CPU_BOARDS { get; set; }
        public string NO_OF_IO_CARDS { get; set; }
        public string STORAGE_NAME { get; set; }
        public string ORACLE_STARTUP_TIME { get; set; }
        public string LOG_MODE { get; set; }
        public string CHARACTERSET { get; set; }
        public string NATIONAL_CHARACTERSET { get; set; }
        public string SESSIONS_CURRENT { get; set; }
        public string SESSIONS_HIGHWATER { get; set; }
        public string BUFFERED_CACHE_MB { get; set; }
        public string REDO_BUFFER_KB { get; set; }
        public string SHARED_POOL_MB { get; set; }
        public string VARIABLE_SGA_MB { get; set; }
        public string TOTAL_SGA_MB { get; set; }
        public string JAVA_POOL_MB { get; set; }
        public string LARGE_POOL_MB { get; set; }
        public string MAXIMUM_SGA_MB { get; set; }
        public string FIXED_SGA_MB { get; set; }
        public string CRITICAL_LEVEL { get; set; }
    }
}
