//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysDocNew
    {
        public int ID { get; set; }
        public string Desc { get; set; }
        public string LinkUrl { get; set; }
        public string LinkType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> sysID { get; set; }
    }
}
