//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemsNote
    {
        public int NoteID { get; set; }
        public int SystemID { get; set; }
        public string NoteDec { get; set; }
        public string NoteData { get; set; }
        public string NoteSubject { get; set; }
        public Nullable<int> TAGNote { get; set; }
    }
}
