//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSectionExtendedField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemSectionExtendedField()
        {
            this.SystemTypeFields = new HashSet<SystemTypeField>();
        }
    
        public int SystemSectionID { get; set; }
        public string SystemSectionDesc { get; set; }
        public int SystemExtenendFieldLayoutID { get; set; }
        public int SystemExtenendFieldWebPartID { get; set; }
    
        public virtual SystemExtenendFieldLayout SystemExtenendFieldLayout { get; set; }
        public virtual SystemExtenendFieldWebPart SystemExtenendFieldWebPart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemTypeField> SystemTypeFields { get; set; }
    }
}
