//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemFileLink
    {
        public int SystemFileLinkID { get; set; }
        public string SystemFileLinkDesc { get; set; }
        public string SystemFileLinkUrl { get; set; }
        public int SystemID { get; set; }
        public Nullable<bool> IsSysDoc { get; set; }
        public Nullable<System.DateTime> DateSysLink { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
