//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemMaintenanceCompany
    {
        public int SystemID { get; set; }
        public int MaintenanceCompanyID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Application Application1 { get; set; }
        public virtual Application Application2 { get; set; }
        public virtual Application Application3 { get; set; }
        public virtual Application Application4 { get; set; }
        public virtual Application Application5 { get; set; }
        public virtual MaintenanceCompany MaintenanceCompany { get; set; }
        public virtual MaintenanceCompany MaintenanceCompany1 { get; set; }
        public virtual MaintenanceCompany MaintenanceCompany2 { get; set; }
        public virtual MaintenanceCompany MaintenanceCompany3 { get; set; }
        public virtual MaintenanceCompany MaintenanceCompany4 { get; set; }
        public virtual MaintenanceCompany MaintenanceCompany5 { get; set; }
    }
}
