//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemTypeField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemTypeField()
        {
            this.SystemExtendedSystemFields = new HashSet<SystemExtendedSystemField>();
        }
    
        public int ID { get; set; }
        public int SystemSection { get; set; }
        public string FieldName { get; set; }
        public int FieldType { get; set; }
        public bool Mandatory { get; set; }
        public string DefaultValue { get; set; }
        public int SystemFieldOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemExtendedSystemField> SystemExtendedSystemFields { get; set; }
        public virtual SystemFieldDataType SystemFieldDataType { get; set; }
        public virtual SystemSectionExtendedField SystemSectionExtendedField { get; set; }
    }
}
