//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaddmImpoterLog
    {
        public int ID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string MessageDate { get; set; }
        public string MessaTime { get; set; }
        public string MessageType { get; set; }
        public string MessageDescription { get; set; }
        public string MessageCause { get; set; }
    }
}
