//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTbl
    {
        public int ID { get; set; }
        public string Item_Name { get; set; }
        public string Application_Name { get; set; }
        public string Application_Owner { get; set; }
    }
}
