//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class testTbl1
    {
        public string ID { get; set; }
        public string DBName { get; set; }
        public string DBInstance { get; set; }
        public string DBHost { get; set; }
        public Nullable<System.DateTime> LastDiscovered { get; set; }
        public string Vendor { get; set; }
        public string Product { get; set; }
        public string Version { get; set; }
        public string DBHostID { get; set; }
    }
}
