//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTRackDemo
    {
        public int id { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<bool> Exist { get; set; }
        public Nullable<int> RackID { get; set; }
    }
}
