//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedStencil
    {
        public int ID { get; set; }
        public int ManufacturerID { get; set; }
        public string FileName { get; set; }
        public long TypeID { get; set; }
        public Nullable<bool> Loaded { get; set; }
    
        public virtual ItemType ItemType { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
