//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserManagentLOG
    {
        public int ID { get; set; }
        public string UserUpdate { get; set; }
        public string OldName { get; set; }
        public string NewName { get; set; }
        public System.DateTime Date { get; set; }
        public string Systems { get; set; }
    }
}
