//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisioMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisioMaster()
        {
            this.MetaItems = new HashSet<MetaItem>();
        }
    
        public int ID { get; set; }
        public int ManufactureID { get; set; }
        public long TypeID { get; set; }
        public string MasterName { get; set; }
        public string FileName { get; set; }
        public Nullable<int> ContainerStarts { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MetaItem> MetaItems { get; set; }
        public virtual VisioMaster VisioMaster1 { get; set; }
        public virtual VisioMaster VisioMaster2 { get; set; }
    }
}
