//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisualizationNote
    {
        public long ID { get; set; }
        public string Text { get; set; }
        public long ItemId { get; set; }
        public int TypeID { get; set; }
        public string BodyText { get; set; }
    }
}
