//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLAN
    {
        public string VilanName { get; set; }
        public int VilanID { get; set; }
        public string FireWall { get; set; }
        public string NetMask { get; set; }
        public string Subnet { get; set; }
        public string Getway { get; set; }
        public string Network { get; set; }
        public string HostStart { get; set; }
        public string HostEnd { get; set; }
        public string BroadcastAddress { get; set; }
        public string Comment { get; set; }
        public string DNSServer { get; set; }
        public string FirstAvalibleIPAddress { get; set; }
        public string VLanNumber { get; set; }
    }
}
