//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_HOST_IMPORT_FROM_IMPORT_TEST
    {
        public int ID { get; set; }
        public int DATACENTER_ID { get; set; }
        public string DNS_NAME { get; set; }
        public string IP_ADDRESS { get; set; }
        public string EXPECTED_SSL_THUMBPRINT { get; set; }
        public string HOST_SSL_THUMBPRINT { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<System.DateTime> PASSWORD_LAST_UPD_DT { get; set; }
        public string IPMI_IP_ADDRESS { get; set; }
        public string IPMI_MAC_ADDRESS { get; set; }
        public string IPMI_USER_NAME { get; set; }
        public string IPMI_PASSWORD { get; set; }
        public int SOAP_PORT { get; set; }
        public int AUTHD_PORT { get; set; }
        public string VPXA_ID { get; set; }
        public string MASTER_GEN { get; set; }
        public string MASTER_SPEC_GEN { get; set; }
        public string UUID_BIOS { get; set; }
        public int ENABLED { get; set; }
        public int VMOTION_ENABLED { get; set; }
        public string LICENSED_EDITION { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_FULLNAME { get; set; }
        public string PRODUCT_VENDOR { get; set; }
        public string PRODUCT_VERSION { get; set; }
        public string PRODUCT_BUILD { get; set; }
        public string PRODUCT_OS_TYPE { get; set; }
        public string PRODUCT_LINE_ID { get; set; }
        public string PRODUCT_API_TYPE { get; set; }
        public string PRODUCT_API_VERSION { get; set; }
        public string CAPABILITY { get; set; }
        public string HOST_VENDOR { get; set; }
        public string HOST_MODEL { get; set; }
        public string CPU_MODEL { get; set; }
        public Nullable<int> CPU_COUNT { get; set; }
        public Nullable<int> CPU_CORE_COUNT { get; set; }
        public Nullable<int> CPU_THREAD_COUNT { get; set; }
        public string NUMA_TYPE { get; set; }
        public string CPU_HZ { get; set; }
        public string MEM_SIZE { get; set; }
        public decimal SMC_PRESENT { get; set; }
        public string CPU_POWER_MGMT_POLICY { get; set; }
        public string CPU_POWER_MGMT_SUPPORT { get; set; }
        public Nullable<int> NIC_COUNT { get; set; }
        public Nullable<int> HBA_COUNT { get; set; }
        public string CONFIG { get; set; }
        public string VM_HARDWARE_INFO { get; set; }
        public string VM_PROV_POLICY { get; set; }
        public string ROOT_RES_CONFIG { get; set; }
        public Nullable<System.DateTime> LAST_PERF_TIME { get; set; }
        public Nullable<int> PERF_REFRESH_RATE { get; set; }
        public Nullable<System.DateTime> BOOT_TIME { get; set; }
        public Nullable<decimal> BOOT_TIME_ON_HOST { get; set; }
        public string DAS_NODE_NAME { get; set; }
        public Nullable<int> MAINTENANCE_MODE { get; set; }
        public Nullable<int> POWER_STATE { get; set; }
        public string DEFAULT_VM_PATH { get; set; }
        public string RESOURCE_INFO { get; set; }
        public string CONFIG_MANAGER { get; set; }
        public string LOCAL_IP_ADDRESS { get; set; }
        public string HOST_KEY { get; set; }
        public decimal ADMIN_DISABLED_FLG { get; set; }
        public string MANAGEMENT_IP { get; set; }
        public decimal FAULTTOLERANCE_ENABLED_FLG { get; set; }
        public Nullable<int> AGENT_VM_DATASTORE_ID { get; set; }
        public Nullable<int> AGENT_VM_NETWORK_ID { get; set; }
        public string LICENSABLE_RESOURCES { get; set; }
        public string ENDORSEMENT_KEY { get; set; }
        public string ATTESTATION_IDENTITY_KEY { get; set; }
        public string NETWORK_RUNTIME_INFO { get; set; }
    }
}
