//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPXImpData
    {
        public int ActId { get; set; }
        public string SConectionStrFrom { get; set; }
        public string SConectionStrTo { get; set; }
        public string SBefor { get; set; }
        public string SQury { get; set; }
        public string SAfter { get; set; }
    }
}
