//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public int ID { get; set; }
        public string AssetNumber { get; set; }
        public string SerialNumber { get; set; }
        public string Description { get; set; }
        public string PurchaseOrder { get; set; }
        public string PurchaseDate { get; set; }
        public string ServiceContactID { get; set; }
        public string InstallDate { get; set; }
        public string Manufacturer { get; set; }
        public string RoleType { get; set; }
        public string ContractEndDate { get; set; }
        public string SYSID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> InsertToItem { get; set; }
        public string Cataloge { get; set; }
        public string Statuse { get; set; }
        public string Name { get; set; }
        public Nullable<long> Parent { get; set; }
        public Nullable<long> RackID { get; set; }
        public Nullable<bool> RearLocation { get; set; }
        public Nullable<int> RelativeLocation { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string IPAddress { get; set; }
        public Nullable<bool> FileLevelBackup { get; set; }
        public string TDPBackup { get; set; }
        public string OSName { get; set; }
        public string FunctionalStation { get; set; }
        public Nullable<int> RoundId { get; set; }
        public Nullable<int> IsComm { get; set; }
        public Nullable<int> IsPassive { get; set; }
        public Nullable<bool> IsServer { get; set; }
        public Nullable<bool> IsFromfile { get; set; }
        public Nullable<int> EnvironmentId { get; set; }
        public string SapLocation { get; set; }
        public string NetoPrice { get; set; }
        public string BelongsTo { get; set; }
        public string Custodian { get; set; }
    }
}
