//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSFileLauncherCatalog
    {
        public long ID { get; set; }
        public Nullable<int> ActionID { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public string WebServiceAddress { get; set; }
        public Nullable<int> MethodID { get; set; }
        public Nullable<int> TimeInterval { get; set; }
        public Nullable<int> TimeIntervalUnits { get; set; }
    }
}
