//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSQueryCatalog
    {
        public int ID { get; set; }
        public int ActionId { get; set; }
        public string Desc { get; set; }
        public string SP_NAME { get; set; }
        public string Return_Field_Names { get; set; }
        public string ReturnTableColName { get; set; }
    }
}
